apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ cookiecutter.name | lower }}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: {{ cookiecutter.owner }}
  lifecycle: experimental
